### ISSUE TITLE
Octal SPI

### ISSUE THREAD

**Issue by fathomtreelimited** [sifive/sifive-blocks#36]
Hi,

Would you consider supporting Octal SPI to interface at full speed with Macronix OctaRAM and OctaFLASH?

http://www.macronix.com/en-us/about/news/Pages/Macronix-Unveils-New-Generation-Low-Pin-Count-OctaBus-Memory-Subsystem-Solution-for-IoT-and-Automotive-Electronics-Markets.aspx

Thanks.

**Comment by richardxia** [comment]
We don't intend to build support for OctaFlash, but we will happily accept pull requests.

**Comment by fathomtreelimited** [comment]
Gladly. :-)
